version: '3'
services:
  mongodb:
    image: docker.io/mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 8081:8081
    volumes:
      - mongodb_volume:/var/lib/db:rw

volumes:
  mongodb_volume: